### ISSUE TITLE
[ADD]: Add contributing.md and CODE OF Conduct

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Question#4]
# Description

We are taking steps to foster a more inclusive and collaborative environment within our open-source project by adding a CONTRIBUTING.md file and a CODE_OF_CONDUCT.md file. These additions will provide clear guidelines for how individuals can contribute to our project and establish a set of behavioral expectations to ensure a respectful and welcoming community.

## Task

- [ ] Add CODE OF CONDUCT
- [ ] Add Contributing.md

## Disclaimer

This issue is reserved for the members of this organization!

**Comment by JYunth** [comment]
I'll add this to the repository, can I get assigned to this?

**Comment by AbhijithGanesh** [comment]
@JYunth yes you may
