### ISSUE TITLE
[FEATURE]: Setup next-theme

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Question#6]
# Description

We are excited to introduce a new feature to our Next.js project: setting up a theme system. A theme system allows us to easily manage the visual appearance and styling of our application, making it more flexible, customizable, and maintainable.

## Tasks
- [ ] Setup [next-themes](https://www.npmjs.com/package/next-themes)

**Comment by HarishChandran3304** [comment]
## Assignment Request
Would love to work on this!
